default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clones_development
test:
  <<: *default
  database: clones_test

production:
  <<: *default
  database: clones_production
  username: clones
  password: <%= ENV['CLONES_DATABASE_PASSWORD'] %>
